### ISSUE TITLE
CPLD pinout? And possible modern alternative?

### ISSUE THREAD

**Issue by Helder1981** [bootsector/smd-sixbutton-encoder#2]
What is the pinout of the CPLD to the buttons on a generic controller for example a common ground button controller? Also is there a source for these CPLD you used? these are no where to be found in most electronic distributors like Mouser or Digikey. Maybe a more readily available CPLD can be used?

Thank you in advance.

**Comment by bootsector** [comment]
Hi there!

You just need a pull-up resistor on each of the buttons input pins. 10K resistors will do fine. Putting the button input pin low activates the button in the output.

Bought some old stock Altera CPLDs from this store: http://cgi.ebay.com/ws/eBayISAPI.dll?ViewItem&item=292579531717

I believe you can use any CPLD from any vendor. Unfortunately 5V based or 5V input tolerant CPLDs are getting rare nowadays. In any can case, you can always add in a voltage translator buffer.

Cheers,

bootsector

**Comment by bootsector** [comment]
Feel free to open a new issue if there are remaining questions. Cheers!
