### ISSUE TITLE
i am intresting on smd-sixbutton-encoder 

### ISSUE THREAD

**Issue by decommand** [bootsector/smd-sixbutton-encoder#3]
hi,
i am intresting on smd-sixbutton-encoder ,may i get full code of the smd-sixbutton-encoder and the circuit schematic based  epm7064slc44?
i wish got your reply, my email  "decommand@gmail.com"
thank you !

**Comment by bootsector** [comment]
Hi! I recommend you to take a look at this project which  uses this implementation and others on the same CPLD. Schematics included: https://github.com/bootsector/usb2classic
